server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: inventory_user
    password: inventory_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      bindings:
        orderCreated-in-0:
          destination: order-created
          content-type: application/json

        inventoryReserved-out-0:
          destination: inventory-reserved
          content-type: application/json

        inventoryReleased-out-0:
          destination: inventory-released
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
