server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/payment
    username: payment_user
    password: payment_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      bindings:
        inventoryReserved-in-0:
          destination: inventory-reserved
          content-type: application/json

        paymentProcessed-out-0:
          destination: payment-processed
          content-type: application/json

        paymentFailed-out-0:
          destination: payment-failed
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      paymentGateway:
        sliding-window-size: 10
        failure-rate-threshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
