server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/payment
    username: payment_user
    password: payment_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      bindings:
        inventoryReserved-in-0:
          destination: inventory-reserved
          content-type: application/json

        paymentProcessed-out-0:
          destination: payment-processed
          content-type: application/json

        paymentFailed-out-0:
          destination: payment-failed
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092
  kafka:
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  timelimiter:
    instances:
      paymentGateway:
        timeout-duration: 500ms

  circuitbreaker:
    instances:
      paymentGateway:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  bulkhead:
    instances:
      paymentGateway:
        max-concurrent-calls: 5
        max-wait-duration: 0

  retry:
    instances:
      paymentGateway:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - java.util.concurrent.TimeoutException




management:
  endpoints:
    web:
      exposure:
        include: health,info
